#-*- mode: org -*-
#+TITLE: Lesson 1
#+STARTUP: latexpreview 

* Типы задач машинного обучения
- Unsupervised learning (Обучение без учителя)
- Reinforcement learning (Обучение с подкреплением)
- Supervised learning (Обучение с учителем)

** Unsupervised learning
Пример задачи:
#+BEGIN_QUOTE
Кластеризация. Разделение аудитории на группы с общими интересами для
эффективной рекламы
#+END_QUOTE

** Reinforcement learning
Основан на том, что алгоритм за каждое свое действие получает награду
или наказание.
Пример: AlphaGo

* Обучение с учителем



$X$ - множество объектов


$ Y $- множество ответов

$y: X \rightarrow Y $ - истинная зависимость

Обучающий датасет - множество наборов из фичей и значений целевой
переменной.
Мы обозначим его $ X_{\text{train}} \subset X $.

$$ X = \begin{pmatrix}
x_{11} & x_{12} & ... & x_{1m} \\
       &  ...   & ... &        \\
x_{n1} & x_{n2} & ... & x_{nm}
\end{pmatrix} $$


$$ Y_{\text{train}} = \begin{pmatrix}
y_1 \\
... \\
y_n
\end{pmatrix} $$

"Учитель" означает, что у нас есть набор объектов для которых ответ
известен (в отличии от unsupervised learning).

$x_{ij}$- признак

** Типы признаков (features):
- Числовые (Numerical)

- Категориальные (Categorical)
  Обычно нужно придумать их числовое представление.
  
- Порядковые (Ordinal)

** Типы задач:
- Классификация (Classification)
  $$ Y = \{0, 1\}, Y = \{1, 2, ..., n\}, Y = \{0, 1\}^n $$

- Регрессия (Regression)
  $$ Y = \mathbb{R} $$

- Ранжирование (Ranking)
  $Y = \{1, 2, ..., n\} $(числа упорядочены)

** Примеры задач
*** Ирисы Фишера
*Какая это задача?*
Есть три вида ириса: setosa, versicolor, virginica.

$$ Y = \{1, 2, 3\} $$. Задача классификации

*Какие есть признаки?*
У них есть 4 параметра: Sepal.Length, Sepal.Width, Petal.Length,
Petal.Width

$$ X = \mathbb{R}^4 $$

Все признаки числовые.

*** Цена дома
Нужно предсказать стоимость дома. Есть датасет со следующими
признаками:
- Удаленность от метро
- Оценка состояния дома(плохое, среднее, хорошее, отличное)
- Колличество комнат
- Площадь
- Год строительства
- Название района, в котором находится дом

*Какая это задача?*

$$ Y = \mathbb{R} $$. Задача регрессии.

*Какие есть признаки?*

Числовые, порядковые, категориальные.

*** Поисковая выдача
Получив запрос от пользователя нужно найти наиболее полезные документы
из некоторой базы.

Что нам известно:
- Запрос пользователя
- Текст документа
- Какие ключевые слова есть в каждом документе.
- Насколько каждый документ популярен
- итд

*Какая это задача?*

$ Y = \{1, 2, ..., n\} $ (числа упорядочены)

Задача ранжирования.

*Какие есть признаки?*

Все сложно, здесь нужно думать...

* KNN
* Обучение моделей
* Линейная регрессия и переобучение
* Алгоритм применения ML к задачам
